### ISSUE TITLE
Repeat last callout

### ISSUE THREAD

**Issue by jchudge** [soundscape-community/soundscape#87] opened 2024-03-18 16:05 UTC
Allow the user to be able to repeat the last callout that Soundscape provided (this could be via a phone shake, voice command, and/or the UI.)

**Comment by ConnorTheDemon** [comment] 2024-05-10 06:40
I've worked on this and have submitted a pull request.

**Comment by steinbro** [comment] 2024-09-24 00:55
Duplicate of #80.

**Closed by steinbro** 2024-09-24 00:55 UTC
Labels: enhancement, help wanted
