### ISSUE TITLE
LOCALISATION: Should the strings "Privacy Policy" and "Services Agreement" be localised?

### ISSUE THREAD

**Issue by StevenAbrams** [soundscape-community/soundscape#53] opened 2023-08-22 17:22 UTC
**Build: 1.0.0 (9)**

**Repro Steps:**
1. Change the language to something non-English e.g., Japanese
2. Go to Soundscape Settings
3. Select the option second from the bottom (About Soundscape)

**Expected Results:**
Everything should be localised on the next UI

**Actual Results:**
The strings "Privacy Policy" and "Services Agreement" are in English

**Comment by steinbro** [comment] 2023-08-23 01:59
That's a reasonable expectation, but for whatever reason, these strings are marked as `GDLocalizationUnnecessary` in the code, meaning the Microsoft developers intended that they not be translated. Maybe because the linked documents were expected to be in English only, so why bother translating a link to a document not available in that language? In any case, unless others feel strongly to the contrary, I'm going to mark this as not a bug.

**Closed by steinbro** 2023-08-23 01:59 UTC
Labels: bug, Localisation, Priority 3, Severity 3
